import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-physician-capitation-settlement-reconciliation",
  "engine": "recovery",
  "title": "Physician Capitation Settlement Reconciliation",
  "shortTitle": "Physician Capitation Settlement Reconciliation",
  "tagline": "Rebuild capitation settlements from member months and contract factors to recover missed revenue and unsupported deductions.",
  "industry": "Provider Network Finance",
  "buyer": "Medical groups, IPAs, and health plans",
  "uiPort": 4657,
  "apiPort": 5657,
  "accent": "#15803d",
  "currency": "USD",
  "primaryOutcome": "Physician Capitation Settlement Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect contracts, member months, risk cells, age-sex factors, retro eligibility, carve-outs, encounters, stop-loss, withholds, settlements, and payments in one accountable workflow. Rebuild capitation settlements from member months and contract factors to recover missed revenue and unsupported deductions.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Physician Capitation Settlement Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("contract-rate-library","PCS01","Contract rate library","Execute contract rate library using contracts, member months, risk cells, age-sex factors, retro eligibility, carve-outs, encounters, stop-loss, withholds, settlements, and payments.","Produce a governed contract rate library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Group / Capitation Contract","text","Group / Capitation Contract · Standard Case"],["caseReference","Contract rate library Reference","text","PCS01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",700000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",847000],["domainDriver","Capitation Model","select","Professional cap",["Professional cap","Global cap","Specialty cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract rate library case","Member month ingestion case","Risk cell mapping case","Age sex factor calculation case","Retro eligibility reconciliation case"]}),
feature("member-month-ingestion","PCS02","Member month ingestion","Execute member month ingestion using contracts, member months, risk cells, age-sex factors, retro eligibility, carve-outs, encounters, stop-loss, withholds, settlements, and payments.","Produce a governed member month ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Group / Capitation Contract","text","Group / Capitation Contract · Standard Case"],["caseReference","Member month ingestion Reference","text","PCS02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",700000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",847000],["domainDriver","Capitation Model","select","Professional cap",["Professional cap","Global cap","Specialty cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract rate library case","Member month ingestion case","Risk cell mapping case","Age sex factor calculation case","Retro eligibility reconciliation case"]}),
feature("risk-cell-mapping","PCS03","Risk cell mapping","Execute risk cell mapping using contracts, member months, risk cells, age-sex factors, retro eligibility, carve-outs, encounters, stop-loss, withholds, settlements, and payments.","Produce a governed risk cell mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Group / Capitation Contract","text","Group / Capitation Contract · Standard Case"],["caseReference","Risk cell mapping Reference","text","PCS03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",700000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",847000],["domainDriver","Capitation Model","select","Professional cap",["Professional cap","Global cap","Specialty cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract rate library case","Member month ingestion case","Risk cell mapping case","Age sex factor calculation case","Retro eligibility reconciliation case"]}),
feature("age-sex-factor-calculation","PCS04","Age sex factor calculation","Execute age sex factor calculation using contracts, member months, risk cells, age-sex factors, retro eligibility, carve-outs, encounters, stop-loss, withholds, settlements, and payments.","Produce a governed age sex factor calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Group / Capitation Contract","text","Group / Capitation Contract · Standard Case"],["caseReference","Age sex factor calculation Reference","text","PCS04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",700000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",847000],["domainDriver","Capitation Model","select","Professional cap",["Professional cap","Global cap","Specialty cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract rate library case","Member month ingestion case","Risk cell mapping case","Age sex factor calculation case","Retro eligibility reconciliation case"]}),
feature("retro-eligibility-reconciliation","PCS05","Retro eligibility reconciliation","Execute retro eligibility reconciliation using contracts, member months, risk cells, age-sex factors, retro eligibility, carve-outs, encounters, stop-loss, withholds, settlements, and payments.","Produce a governed retro eligibility reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Group / Capitation Contract","text","Group / Capitation Contract · Standard Case"],["caseReference","Retro eligibility reconciliation Reference","text","PCS05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",700000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",847000],["domainDriver","Capitation Model","select","Professional cap",["Professional cap","Global cap","Specialty cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract rate library case","Member month ingestion case","Risk cell mapping case","Age sex factor calculation case","Retro eligibility reconciliation case"]}),
feature("carve-out-validation","PCS06","Carve-out validation","Execute carve-out validation using contracts, member months, risk cells, age-sex factors, retro eligibility, carve-outs, encounters, stop-loss, withholds, settlements, and payments.","Produce a governed carve-out validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Group / Capitation Contract","text","Group / Capitation Contract · Standard Case"],["caseReference","Carve-out validation Reference","text","PCS06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",700000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",847000],["domainDriver","Capitation Model","select","Professional cap",["Professional cap","Global cap","Specialty cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract rate library case","Member month ingestion case","Risk cell mapping case","Age sex factor calculation case","Retro eligibility reconciliation case"]}),
feature("encounter-completeness","PCS07","Encounter completeness","Execute encounter completeness using contracts, member months, risk cells, age-sex factors, retro eligibility, carve-outs, encounters, stop-loss, withholds, settlements, and payments.","Produce a governed encounter completeness decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Group / Capitation Contract","text","Group / Capitation Contract · Standard Case"],["caseReference","Encounter completeness Reference","text","PCS07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",700000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",847000],["domainDriver","Capitation Model","select","Professional cap",["Professional cap","Global cap","Specialty cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract rate library case","Member month ingestion case","Risk cell mapping case","Age sex factor calculation case","Retro eligibility reconciliation case"]}),
feature("stop-loss-recovery","PCS08","Stop-loss recovery","Execute stop-loss recovery using contracts, member months, risk cells, age-sex factors, retro eligibility, carve-outs, encounters, stop-loss, withholds, settlements, and payments.","Produce a governed stop-loss recovery decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Group / Capitation Contract","text","Group / Capitation Contract · Standard Case"],["caseReference","Stop-loss recovery Reference","text","PCS08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",700000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",847000],["domainDriver","Capitation Model","select","Professional cap",["Professional cap","Global cap","Specialty cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract rate library case","Member month ingestion case","Risk cell mapping case","Age sex factor calculation case","Retro eligibility reconciliation case"]}),
feature("withhold-calculation","PCS09","Withhold calculation","Execute withhold calculation using contracts, member months, risk cells, age-sex factors, retro eligibility, carve-outs, encounters, stop-loss, withholds, settlements, and payments.","Produce a governed withhold calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Group / Capitation Contract","text","Group / Capitation Contract · Standard Case"],["caseReference","Withhold calculation Reference","text","PCS09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",700000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",847000],["domainDriver","Capitation Model","select","Professional cap",["Professional cap","Global cap","Specialty cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract rate library case","Member month ingestion case","Risk cell mapping case","Age sex factor calculation case","Retro eligibility reconciliation case"]}),
feature("quality-pool-allocation","PCS10","Quality pool allocation","Execute quality pool allocation using contracts, member months, risk cells, age-sex factors, retro eligibility, carve-outs, encounters, stop-loss, withholds, settlements, and payments.","Produce a governed quality pool allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Group / Capitation Contract","text","Group / Capitation Contract · Standard Case"],["caseReference","Quality pool allocation Reference","text","PCS10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",700000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",847000],["domainDriver","Capitation Model","select","Professional cap",["Professional cap","Global cap","Specialty cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract rate library case","Member month ingestion case","Risk cell mapping case","Age sex factor calculation case","Retro eligibility reconciliation case"]}),
feature("risk-corridor-settlement","PCS11","Risk corridor settlement","Execute risk corridor settlement using contracts, member months, risk cells, age-sex factors, retro eligibility, carve-outs, encounters, stop-loss, withholds, settlements, and payments.","Produce a governed risk corridor settlement decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Group / Capitation Contract","text","Group / Capitation Contract · Standard Case"],["caseReference","Risk corridor settlement Reference","text","PCS11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",700000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",847000],["domainDriver","Capitation Model","select","Professional cap",["Professional cap","Global cap","Specialty cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract rate library case","Member month ingestion case","Risk cell mapping case","Age sex factor calculation case","Retro eligibility reconciliation case"]}),
feature("payment-statement-matching","PCS12","Payment statement matching","Execute payment statement matching using contracts, member months, risk cells, age-sex factors, retro eligibility, carve-outs, encounters, stop-loss, withholds, settlements, and payments.","Produce a governed payment statement matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Group / Capitation Contract","text","Group / Capitation Contract · Standard Case"],["caseReference","Payment statement matching Reference","text","PCS12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",700000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",847000],["domainDriver","Capitation Model","select","Professional cap",["Professional cap","Global cap","Specialty cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract rate library case","Member month ingestion case","Risk cell mapping case","Age sex factor calculation case","Retro eligibility reconciliation case"]}),
feature("variance-dispute-workflow","PCS13","Variance dispute workflow","Execute variance dispute workflow using contracts, member months, risk cells, age-sex factors, retro eligibility, carve-outs, encounters, stop-loss, withholds, settlements, and payments.","Produce a governed variance dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Group / Capitation Contract","text","Group / Capitation Contract · Standard Case"],["caseReference","Variance dispute workflow Reference","text","PCS13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",700000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",847000],["domainDriver","Capitation Model","select","Professional cap",["Professional cap","Global cap","Specialty cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract rate library case","Member month ingestion case","Risk cell mapping case","Age sex factor calculation case","Retro eligibility reconciliation case"]}),
feature("cash-reconciliation","PCS14","Cash reconciliation","Execute cash reconciliation using contracts, member months, risk cells, age-sex factors, retro eligibility, carve-outs, encounters, stop-loss, withholds, settlements, and payments.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Group / Capitation Contract","text","Group / Capitation Contract · Standard Case"],["caseReference","Cash reconciliation Reference","text","PCS14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",700000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",847000],["domainDriver","Capitation Model","select","Professional cap",["Professional cap","Global cap","Specialty cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract rate library case","Member month ingestion case","Risk cell mapping case","Age sex factor calculation case","Retro eligibility reconciliation case"]}),
feature("group-plan-analytics","PCS15","Group plan analytics","Execute group plan analytics using contracts, member months, risk cells, age-sex factors, retro eligibility, carve-outs, encounters, stop-loss, withholds, settlements, and payments.","Produce a governed group plan analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Group / Capitation Contract","text","Group / Capitation Contract · Standard Case"],["caseReference","Group plan analytics Reference","text","PCS15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",700000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",847000],["domainDriver","Capitation Model","select","Professional cap",["Professional cap","Global cap","Specialty cap"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract rate library case","Member month ingestion case","Risk cell mapping case","Age sex factor calculation case","Retro eligibility reconciliation case"]})
]);
